// Giant Brand
var num_items_giant = 38;

var bike_pics_giant = ["pictures/bikes/2016/road/Propel/Propel-Adv-SL-0/Propel-Advanced-SL-0-Comp.jpg",
				 "pictures/bikes/2016/road/Propel/Propel-Adv-SL-Team/Propel-Adv-SL-Team.jpg",
				 "pictures/bikes/2016/road/Propel/Propel-Adv-SL-1/Propel-Advanced-SL-1-Blue.jpg",
				 "pictures/bikes/2016/road/Propel/Propel-Adv-SL-2/Propel-Advanced-SL-2-Comp-Red.jpg",
				 "pictures/bikes/2016/road/Propel/Propel-Adv-Pro-0/Propel-Advanced-Pro-0-Comp.jpg",
				 "pictures/bikes/2016/road/Propel/Propel-Adv-0/Propel-Advanced-0-Comp.jpg", 
				 "pictures/bikes/2016/road/Propel/Propel-Adv-1/Propel-Advanced-1-Comp.jpg",
				 "pictures/bikes/2016/road/Propel/Propel-Adv-2/Propel-Advanced-2-Comp-White.jpg", 
				 "pictures/bikes/2016/road/TCR/TCR-Adv-SL-0/TCR-Advanced-SL-0-Copmp-Cyan.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-SL-1/TCR-Advanced-SL-1-Comp-Red.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-SL-2/TCR-Advanced-SL-2-Lime-Black.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-Pro-0/TCR-Advanced-Pro-0-Comp-Black.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-Pro-1/TCR-Advanced-Pro-1-Comp-Cyan.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-1/TCR-Advanced-1-Comp-Lime.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-2/TCR-Advanced-2-Comp-Red.jpg",
				 "pictures/bikes/2016/road/TCR/TCR-Adv-3/TCR-Advanced-3-Comp-Yellow.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-SL-0/Defy-Advanced-SL-0-Comp-Blue.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-SL-1/Defy-Advanced-SL-1-Comp-Red.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-Pro-0/Defy-Advanced-Pro-0-Comp.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-Pro-2/Defy-Advanced-Pro-2-Blue.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-1/Defy-Advanced-1-Comp-Cyan.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-2/Defy-Advanced-2-Comp-Lime.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-Adv-3/Defy-Advanced-3-Comp.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-1/Defy-1-Disc-Blue.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-2/Defy-2-Disc-Black.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-3/Defy-3-White.jpg",
				 "pictures/bikes/2016/road/Defy/Defy-5/Defy-5-Black-Red.jpg",
				 "pictures/bikes/2016/road/Fastroad/Fastroad-Comax-1/FastRoad-CoMax-1.jpg",
				 "pictures/bikes/2016/road/Fastroad/Fastroad-Comax-2/FastRoad-CoMax-2-Comp-Blue.jpg",
				 "pictures/bikes/2016/road/Fastroad/Fastroad-SLR-1/FastRoad-SLR-1-Black.jpg",
				 "pictures/bikes/2016/road/Escape/Escape-1/Escape-1-Black.jpg",
				 "pictures/bikes/2016/road/Escape/Escape-2/Escape-2-Gray.jpg",
				 "pictures/bikes/2016/road/Escape/Escape-2-City/Escape-2-City-Gray.jpg",
				 "pictures/bikes/2016/road/Escape/Escape-3/Escape-3-Black.jpg",
				 "pictures/bikes/2016/road/Cypress/Cypress-DX/Cypress-DX-Dark-Gray.jpg",
				 "pictures/bikes/2016/road/Cypress/Cypress/Cypress-Black.jpg",
				 "pictures/bikes/2016/road/Simple/Three/Simple-Three-Green.jpg",
				 "pictures/bikes/2016/road/Simple/Single/Simple-Single-Red-Black.jpg"];

var bike_titles_giant = ["Giant Propel Advanced SL 0",
				   "Giant Propel Advanced SL Team",
				   "Giant Propel Advanced SL 1",
				   "Giant Propel Advanced SL 2",
				   "Giant Propel Advanced Pro 0",
				   "Giant Propel Advanced 0",
				   "Giant Propel Advanced 1",
				   "Giant Propel Advanced 2",
				   "Giant TCR Advanced SL 0",
				   "Giant TCR Advanced SL 1",
				   "Giant TCR Advanced SL 2",
				   "Giant TCR Advanced Pro 0",
				   "Giant TCR Advanced Pro 1",
				   "Giant TCR Advanced 1",
				   "Giant TCR Advanced 2",
				   "Giant TCR Advanced 3",
				   "Giant Defy Advanced SL 0",
				   "Giant Defy Advanced SL 1",
				   "Giant Defy Advanced Pro 0",
				   "Giant Defy Advanced Pro 2",
				   "Giant Defy Advanced 1",
				   "Giant Defy Advanced 2",
				   "Giant Defy Advanced 3",
				   "Giant Defy 1 Disc",
				   "Giant Defy 2 Disc",
				   "Giant Defy 3",
				   "Giant Defy 5",
				   "Giant Fastroad CoMax 1",
				   "Giant Fastroad CoMax 2",
				   "Giant Fastroad SLR 1",
				   "Giant Escape 1",
				   "Giant Escape 2",
				   "Giant Escape 2 City",
				   "Giant Escape 3",
				   "Giant Cypress DX",
				   "Giant Cypress",
				   "Giant Simple Three",
				   "Giant Simple Single"];

var bike_descriptions_giant = ["This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$9000</strong>",
						 "This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$6900</strong>",
						 "This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$6900</strong>",
						 "This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$4400</strong>",
						 "A perfect blend of aero efficiency and all-around ride quality. For the spring, the chase, the thrill of speed.<br><strong>$5650</strong>",
						 "Get up to speed and slice through the wind. Whether springing to win or riding solo, give yourself the aero edge.<br><strong>$4000</strong>",
						 "Get up to speed and slice through the wind. Whether springing to win or riding solo, give yourself the aero edge.<br><strong>$2600</strong>",
						 "Get up to speed and slice through the wind. Whether springing to win or riding solo, give yourself the aero edge.<br><strong>$2100</strong>",
						 "Fly up steep climbs. Attack twisting descents. Now lighter and more efficient, this reengineered pro legend is the total race bike.<br><strong>$9000</strong>",
						 "Fly up steep climbs. Attack twisting descents. Now lighter and more efficient, this reengineered pro legend is the total race bike.<br><strong>$5900</strong>",
						 "Fly up steep climbs. Attack twisting descents. Now lighter and more efficient, this reengineered pro legend is the total race bike.<br><strong>$4100</strong>",
						 "From long, hard training rides to critical moments in a race. This is total race performance, made for your podium quest.<br><strong>$5500</strong>",
						 "From long, hard training rides to critical moments in a race. This is total race performance, made for your podium quest.<br><strong>$3500</strong>",
						 "Race-winning efficiency. Improved ride quality. Agile geometry. New and updated, the total race bike for road.<br><strong>$2500</strong>",
						 "Race-winning efficiency. Improved ride quality. Agile geometry. New and updated, the total race bike for road.<br><strong>$2000</strong>",
						 "Race-winning efficiency. Improved ride quality. Agile geometry. New and updated, the total race bike for road.<br><strong>$1700</strong>",
						 "Peak performance to push yourself farther. Superlight and smooth riding, this is the new standard for endurance road.<br><strong>$8300</strong>",
						 "Peak performance to push yourself farther. Superlight and smooth riding, this is the new standard for endurance road.<br><strong>$4600</strong>",
						 "No gimmicks, just superior engineering for compliance and control. Ride faster, ride farther on all types of roads.<br><strong>$5100</strong>",
						 "No gimmicks, just superior engineering for compliance and control. Ride faster, ride farther on all types of roads.<br><strong>$3200</strong>",
						 "Hammer out more miles, descend with more confidence. From Gran Fondos to epic solo rides, Defy Advanced helps you finish strong.<br><strong>$2600</strong>",
						 "Hammer out more miles, descend with more confidence. From Gran Fondos to epic solo rides, Defy Advanced helps you finish strong.<br><strong>$2100</strong>",
						 "Hammer out more miles, descend with more confidence. From Gran Fondos to epic solo rides, Defy Advanced helps you finish strong.<br><strong>$1800</strong>",
						 "Light and lively road performance with an added boost of compliance and control. Smooth, fast and fun to ride.<br><strong>$1500</strong>",
						 "Light and lively road performance with an added boost of compliance and control. Smooth, fast and fun to ride.<br><strong>$1200</strong>",
						 "Get fit, get fast, and get more miles with this lightweight, smooth and comfortable aluminum road machine.<br><strong>$920</strong>",
						 "Get fit, get fast, and get more miles with this lightweight, smooth and comfortable aluminum road machine.<br><strong>$640</strong>",
						 "Get up to speed with less effort and more fun. This sporty, smooth-riding flat-bar road bike is pure exhiliration.<br><strong>$1800</strong>",
						 "Get up to speed with less effort and more fun. This sporty, smooth-riding flat-bar road bike is pure exhiliration.<br><strong>$1500</strong>",
						 "So smooth, so efficient, it feels like flying. A sleek road bike meets flat-bar positioning. Super versatile, super fun.<br><strong>$1100</strong>",
						 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$670</strong>",
						 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$460</strong>",
						 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$590</strong>",
						 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$360</strong>",
						 "Comfort, control and the joy of a bike ride. Cypress helps you get outside, get healthy and get where you want to go.<br><strong>$440</strong>",
						 "Comfort, control and the joy of a bike ride. Cypress helps you get outside, get healthy and get where you want to go.<br><strong>$340</strong>",
						 "Hop on, spin the pedals, and feel the stress melt away. Class cruiser style meets modern comfort and design.<br><strong>$490</strong>",
						 "Hop on, spin the pedals, and feel the stress melt away. Class cruiser style meets modern comfort and design.<br><strong>$330</strong>"];

var bike_modal_descriptions_giant = ["<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600043\"></iframe>",
						        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=651001\"></iframe>",
						        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600044\"></iframe>",
						       "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600045\"></iframe>",
						        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600040\"></iframe>",
						        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600020\"></iframe>",
						       "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600021\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600022\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600052\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600053\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600054\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600049\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600050\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600046\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600047\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600048\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600034\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600035\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600031\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600033\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600015\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600016\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600017\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600029\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600030\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600012\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600014\"></iframe>",
				   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600115\"></iframe>"];

// Liv Brand
var num_items_liv = 8;

var bike_pics_liv = ["pictures/bikes/2016/mtb/Lust/Lust-1/Lust-1-Blue.jpg",
					 "pictures/bikes/2016/mtb/Lust/Lust-2/Lust-2-Black-Pink.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-1/Tempt-1-Black.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-2/Tempt-2-White.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-3/Tempt-3-Dark-Green.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-4/Tempt-4-Black.jpg",
					 "pictures/bikes/2016/mtb/Enchant/Enchant-1/Enchant-1-Black-Purple.jpg",
					 "pictures/bikes/2016/mtb/Enchant/Enchant-2/Enchant-2-White-Blue.jpg"];

var bike_titles_liv = ["Liv Lust 1",
					   "Liv Lust 2",
					   "Liv Tempt 1",
					   "Liv Tempt 2",
					   "Liv Tempt 3",
					   "Liv Tempt 4",
					   "Liv Enchant 1",
					   "Liv Enchant 2"];

var bike_descriptions_liv = ["The trifecta of less weight, more control, and increased efficiency equals a fun and confident XC bike.<br><strong>$2900</strong>",
							 "The trifecta of less weight, more control, and increased efficiency equals a fun and confident XC bike.<br><strong>$2500</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$1400</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$1100</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$700</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$600</strong>",
							 "Become enchanted with cycling on roads, paths or dirt. The versatile and capable enchant.<br><strong>$430</strong>",
							 "Become enchanted with cycling on roads, paths or dirt. The versatile and capable enchant.<br><strong>$370</strong>"];

var bike_modal_titles_liv = ["Live Lust 1",
				   			 "Liv Lust 2",
				   			 "Liv Tempt 1",
							 "Liv Tempt  2",
							 "Liv Tempt 3",
							 "Liv Tempt 4",
							 "Liv Enchant 1",
							 "Liv Enchant 2"];

var bike_modal_descriptions_liv = ["This is a test modal body",
						    	   "This is a test modal body",
						           "This is a test modal body",
						    	   "This is a test modal body",
						    	   "This is a test modal body",
						           "This is a test modal body",
						           "This is a test modal body",
						           "THis is a test bodal body"];

// Kona Brand
var num_items_kona = 4;

var bike_pics_kona = ["pictures/bikes/2016/mtb/Anthem/Anthem-X-29er-Black.jpg",
					  "pictures/bikes/2016/mtb/Trance/Trance-27.5-2/Trance-275-2-Charcoal.jpg",
					  "pictures/bikes/2016/mtb/Trance/Trance-27.5-3/Trance-275-3-Black.jpg",
					  "pictures/bikes/2016/mtb/Stance/Stance-27.5-2/Stance-275-2-Black.jpg",
					  "pictures/bikes/2016/mtb/Talon/Talon-27.5-1/Talon-275-1-Black-Green.jpg",
					  "pictures/bikes/2016/mtb/Talon/Talon-27.5-2/Talon-275-2-Silver-Blue.jpg", 
					  "pictures/bikes/2016/mtb/Talon/Talon-27.5-3/Talon-27-5-3-Charcoal.jpg",
					  "pictures/bikes/2016/mtb/ATX/ATX-275-2-Black-Red.jpg", 
					  "pictures/bikes/2016/mtb/Revel/Revel-2/Revel-2-Black.jpg"];

var bike_titles_kona = ["Giant Anthem X 29er",
				   "Giant Trance 27.5 2",
				   "Giant Trance 27.5 3",
				   "Giant Stance 27.5 2",
				   "Giant Talon 27.5 1",
				   "Giant Talon 27.5 2",
				   "Giant Talon 27.5 3",
				   "Giant ATX 27.5 2",
				   "Giant Revel 2"];

var bike_descriptions_kona = ["Smooth, stable and in control. Crush technical terrain with this confident XC roller.<br><strong>$2700</strong>",
						 "More control on steep, aggressive terrain, power and speed on technical climbs. Pure confidence for every type of trail.<br><strong>$2700</strong>",
						 "More control on steep, aggressive terrain, power and speed on technical climbs. Pure confidence for every type of trail.<br><strong>$2100</strong>",
						 "When the trail calls, Stance 27.5 answers. Confident, quick and fun to ride, it opens up a world of off-road possibilities.<br><strong>$1500</strong>",
						 "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$1400</strong>",
						 "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$1100</strong>",
						 "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$700</strong>",
						 "On-road or off-road, the choice is yours. With smooth, confident 27.5 wheels, this is your invitation to explore.<br><strong>$460</strong>",
						 "Take a spin on the bike path or head into the forest. For aspiring off-road riders, revel lets you blaze new trails.<br><strong>$370</strong>"];

var bike_modal_titles_kona = ["Giant Anthem X 29er",
				   		  "Giant Trance 27.5 2",
				   		  "Giant Trance 27.5 3",
						  "Giant Stance 27.5 2",
						  "Giant Talon 27.5 1",
						  "Giant Talon 27.5 2",
						  "Giant Talon 27.5 3",
						  "Giant ATX 27.5 2",
						  "Giant Revel 2"];

var bike_modal_descriptions_kona = ["This is a test modal body",
						        "This is a test modal body",
						        "This is a test modal body",
						       "This is a test modal body",
						        "This is a test modal body",
						        "This is a test modal body",
						       "This is a test modal body",
				   		        "This is a test modal body",
				   		        "This is a test modal body"];