var num_items_giant = 15;

var bike_pics_giant = ["pictures/bikes/2016/xroad/TCX/TCX-Adv-Pro-1/TCX-Advanced-Pro-1-Comp-White.jpg",
					   "pictures/bikes/2016/xroad/TCX/TCX-Adv-Pro-2/TCX-Advanced-Pro-2-Comp-Silver.jpg",
					   "pictures/bikes/2016/xroad/TCX/TCX-SLR-2/TCX-SLR-2-Black-White.jpg",
					   "pictures/bikes/2016/xroad/Revolt/Revolt-1/Revolt-1-Dark-Blue-1.jpg",
					   "pictures/bikes/2016/xroad/Revolt/Revolt-3/Revolt-3-Gray.jpg",
					   "pictures/bikes/2016/xroad/Anyroad/Anyroad-Comax/AnyRoad-CoMax-Charcoal.jpg",
					   "pictures/bikes/2016/xroad/Anyroad/Anyroad-1/AnyRoad-1-Dark-Blue.jpg",
					   "pictures/bikes/2016/xroad/Anyroad/Anyroad-2/AnyRoad-2-Black.jpg",
					   "pictures/bikes/2016/xroad/Toughroad/Toughroad-SLR-1/ToughRoad-SLR-1-Black-Red.jpg",
					   "pictures/bikes/2016/xroad/Toughroad/Toughroad-SLR-2/ToughRoad-SLR-2-Black.jpg",
					   "pictures/bikes/2016/xroad/Roam/Roam-1-Disc/Roam-1-Disc-Black.jpg",
					   "pictures/bikes/2016/xroad/Roam/Roam-2-Disc/Roam-2-Disc-Slate-Gray.jpg",
					   "pictures/bikes/2016/xroad/Roam/Roam-3/Roam-3-Black.jpg",
					   "pictures/bikes/2016/xroad/Sedona/Sedona-DX/Sedona-DX-Charcoal.jpg",
					   "pictures/bikes/2016/xroad/Sedona/Sedona/Sedona-Black.jpg"];

var bike_titles_giant = ["Giant TCX Advanced Pro 1",
						 "Giant TCX Advanced Pro 2",
						 "Giant SLR 2",
						 "Giant Revolt 1",
						 "Giant Revolt 3",
						 "Giant AnyRoad CoMax",
						 "Giant AnyRoad 1",
						 "Giant AnyRoad 2",
						 "Giant ToughRoad 1",
						 "Giant ToughRoad 2",
						 "Giant Roam 1",
						 "Giant Roam 2",
						 "Giant Roam 3",
						 "Giant Sedona DX",
						 "Giant Sedona"];

var bike_descriptions_giant = ["World cup pedigree, cutting-edge innovation. For fierce CX battles in the dirt, mud or snow, this is your winning move.<br><strong>$4500</strong>",
							   "World cup pedigree, cutting-edge innovation. For fierce CX battles in the dirt, mud or snow, this is your winning move.<br><strong>$2700</strong>",
							   "Attack at the start, hammer out laps. From tight CX courses to wide-open gravel and dirt, this 'cross machine does it all.<br><strong>$1600</strong>",
							   "Pedal into the unknown, then keep on going. Ride farther on the road, gravel or dirt with the adventurous Revolt.<br><strong>$1300</strong>",
							   "Road, gravel or dirt - why limit your options? Revolt lets you extend the adventure and pedal into the unknown.<br><strong>$1050</strong>",
							   "A bike build for versatility can also be quick. This agine composite all-rounder does it all with speed and style.<br><strong>$1900</strong>",
							   "Sometimes you just want to ride. Smooth roads, rough roads, rain or shine. With the friendly, inviting AnyRoad, just hop on and go.<br><strong>$1300</strong>",
							   "Sometimes you just want to ride. Smooth roads, rough roads, rain or shine. With the friendly, inviting AnyRoad, just hop on and go.<br><strong>$1100</strong>",
							   "Fly through city streets, up a mountain, down a rugged dirt path. All on one ride, all on one quick and capable machine.<br><strong>$1300</strong>",
							   "Fly through city streets, up a mountain, down a rugged dirt path. All on one ride, all on one quick and capable machine.<br><strong>$870</strong>",
							   "The confidence and capabilities of a mountain bike plus the smooth efficiency of a road bike. Ride everywhere with Roam.<br><strong>$840</strong>",
							   "The confidence and capabilities of a mountain bike plus the smooth efficiency of a road bike. Ride everywhere with Roam.<br><strong>$670</strong>",
							   "The confidence and capabilities of a mountain bike plus the smooth efficiency of a road bike. Ride everywhere with Roam.<br><strong>$460</strong>",
							   "Turn everyday rides into mini adventures. Sedona is motivation to get outside and enjoy the cycling life.<br><strong>$440</strong>",
							   "Turn everyday rides into mini adventures. Sedona is motivation to get outside and enjoy the cycling life.<br><strong>$360</strong>"];

var bike_modal_descriptions_giant = ["<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600505\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600506\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600508\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600502\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600504\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600511\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600509\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600510\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600528\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600529\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600520\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600521\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600522\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=631502\"></iframe>",
									 "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=631501\"></iframe>"];

var num_items_liv = 8;

var bike_pics_liv = ["pictures/bikes/2016/kids/Enchant-24/Enchant-1-24-Purple.jpg",
				 	 "pictures/bikes/2016/kids/Enchant-24-Lite/Enchant-24-Lite-White.jpg",
				 	 "pictures/bikes/2016/kids/Enchant-20/Enchant-20-Lite-Blue.jpg",
				 	 "pictures/bikes/2016/kids/Bella/Bella-Aqua.jpg",
				 	 "pictures/bikes/2016/kids/Adore/Adore-CB-16-White.jpg",
				 	 "pictures/bikes/2016/kids/Adore/Adore-CB-12-Pink.jpg",
				 	 "pictures/bikes/2016/kids/Blossom/Blossom-CB-Profile-purple-medium.jpg"];

var bike_titles_liv = ["Liv Enchant 24",
					   "Liv Enchant 24 Lite",
				  	   "Liv Enchant 20 Lite",
				  	   "Live Bella 20",
				  	   "Liv Adore 16",
					   "Liv Adore 12",
					   "Liv Blossom"];

var bike_descriptions_liv = ["What makes trail riding fun for kids? It starts with the right bike. Enchant ensures smooth sailing, even on bumpy trails.<br><strong>$340</strong>",
							 "Lightweight and easy to maneuver, Enchant Lite puts her on a path to adventure.<br><strong>$255</strong>",
						 	 "Lightweight and easy to maneuver, Enchant Lite puts her on a path to adventure.<br><strong>$235</strong>",
							 "Spark her sense of adventure. Bella is built to ignite a love for cycling and ourdoor activities.<br><strong>$210</strong>",
							 "Her first two-wheeler. One of life's greatest experiences. Stable, safe, and fun, The colorful Adore makes it easy.<br><strong>$190</strong>",
							 "Her first two-wheeler. One of life's greatest experiences. Stable, safe, and fun, The colorful Adore makes it easy.<br><strong>$180</strong>",
							 "Young ones grow up, and Blossom grows with them. Colors she'll love, and a lasting design that you'll love too.<br><strong>$240</strong>"];

var bike_modal_descriptions_liv = ["This is a test modal body",
						    	   "This is a test modal body",
						           "This is a test modal body",
						    	   "This is a test modal body",
						           "This is a test modal body",
						           "This is a test modal body",
						    	   "This is a test modal body",
				   		           "This is a test modal body"];