<?php
								$buttonNum = $_POST['num'];
								$num_items_giant = 35;
								$bike_modal_descriptions_giant = array('<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640304"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600305"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600306"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640304"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600302"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640302"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640305"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640303"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600336"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600337"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600333"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600335"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640311"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640312"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600330"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600331"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600332"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600327"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600328"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600329"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640309"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600325"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600326"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600323"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600324"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600321"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600322"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600402"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600403"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600404"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600405"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640402"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600516"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600411"></iframe>',
									 '<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=616403"></iframe>');
								
								
								$bike_titles_giant = array("Giant Anthem Advanced 27.5 0",
																"Giant Anthem Advanced 27.5 1",
																"Giant Anthem Advanced 27.5 2",
																"Giant Anthem Advanced SX 27.5",
																"Giant Anthem 27.5 2",
																"Giant Anthem SX 27.5",
																"Giant Anthem X Advanced 29er",
																"Giant Anthem X 29er",
																"Giant XTC Advanced SL 27.5 0",
																"Giant XTC Advanced SL 27.5 1",
																"Giant XTC Advanced 27.5 1",
																"Giant XTC Advanced 27.5 3",
																"Giant XTC Advanced 29er 1",
																"Giant XTC Advanced 29er 2",
																"Giant Trance Advanced 27.5 0",
																"Giant Trance Advanced 27.5 1",
																"Giant Trance Advanced 27.5 2",
																"Giant Trance 27.5 1",
																"Giant Trance 27.5 2",
																"Giant Trance 27.5 3",
																"Giant Trance SX 27.5",
																"Giant Stance 27.5 1",
																"Giant Stance 27.5 2",
																"Giant Reign Advanced 27.5 0",
																"Giant Reign Advanced 27.5 1",
																"Giant Reign 27.5 1",
																"Giant Reign 27.5 2",
																"Giant Talon 27.5 1",
																"Giant Talon 27.5 2",
																"Giant Talon 27.5 3",
																"Giant Talon 27.5 4",
																"Giant Talon 29er",
																"Giant ATX 27.5 2",
																"Giant Revel 2",
																"Giant Revel 29er");
								
						      print '<div class="modal-content" id="modal-content">'
								. '<div class="modal-header">'
						          . '<button type="button" class="close" data-dismiss="modal">&times;</button>'
						          . '<h4 class="modal-title">' . $bike_titles_giant[$buttonNum] . '</h4>'
						        . '</div>'
						        . '<div class="modal-body">'
						          . '<p>' . $bike_modal_descriptions_giant[$buttonNum] . '</p>'
						        . '</div>'
						        . '<div class="modal-footer">'
						          . '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>'
						        . '</div>'
								. '</div>';
								
								
								
								/*// Giant Brand
var num_items_giant = 35;

var bike_pics_giant = ["pictures/bikes/2016/mtb/Anthem/Anthem-Adv-275-0/Anthem-Advanced-275-0-Comp-Blue.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-Adv-275-1/Anthem-Advanced-275-1-Yellow-Black.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-Adv-275-2/Anthem-Advanced-275-2-Comp-Red.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-Adv-SX-275/Anthem-Advanced-SX-275-Green.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-275-2/Anthem-275-2.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-SX-275/Anthem-SX-275-2-Black-Green.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-X-Adv-29er/Anthem-X-Advanced-29er-Comp.jpg",
					   "pictures/bikes/2016/mtb/Anthem/Anthem-X-29er/Anthem-X-29er-Black.jpg",
					   "pictures/bikes/2016/mtb/XTC/XTC-Adv-SL-275-0/XtC-Advanced-SL-275-0-Comp.jpg",
					   "pictures/bikes/2016/mtb/XTC/XTC-Adv-SL-275-1/XtC-Advanced-SL-275-1-Lime.jpg",
					   "pictures/bikes/2016/mtb/XTC/XTC-Adv-275-1/XtC-Advanced-275-1-Comp.jpg",
					   "pictures/bikes/2016/mtb/XTC/XTC-Adv-275-3/XtC-Advanced-275-3-Comp-Yellow.jpg",
					   "pictures/bikes/2016/mtb/XTC/XTC-Adv-29er-1/XtC-Advanced-29er-1-Comp-Green.jpg",
					   "pictures/bikes/2016/mtb/XTC/XTC-Adv-29er-2/XtC-Advanced-29er-2-Comp-White.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-Adv-275-0/Trance-Advanced-275-0-Grayish-Green.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-Adv-275-1/Trance-Advanced-275-1-Comp-Orange.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-Adv-275-2/Trance-Advanced-275-2-Comp.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-275-1/Trance-275-1-Grayish-Green.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-275-2/Trance-275-2-Charcoal.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-275-3/Trance-275-3-Black.jpg",
					   "pictures/bikes/2016/mtb/Trance/Trance-SX-275/Trance-SX-275-Blue.jpg",
					   "pictures/bikes/2016/mtb/Stance/Stance-275-1/Stance-275-1-Dark-Blue.jpg",
					   "pictures/bikes/2016/mtb/Stance/Stance-275-2/Stance-275-2-Black.jpg",
					   "pictures/bikes/2016/mtb/Reign/Reign-Advanced-275-0/Reign-Advanced-275-0-Blue-Black.jpg",
					   "pictures/bikes/2016/mtb/Reign/Reign-Advanced-275-1/Reign-Advanced-275-1-Green.jpg",
					   "pictures/bikes/2016/mtb/Reign/Reign-275-1/Reign-275-1-Black.jpg",
					   "pictures/bikes/2016/mtb/Reign/Reign-275-2/Reign-275-2-Yellow-Blue.jpg",
					   "pictures/bikes/2016/mtb/Talon/Talon-27.5-1/Talon-275-1-Black-Green.jpg",
					   "pictures/bikes/2016/mtb/Talon/Talon-27.5-2/Talon-275-2-Silver-Blue.jpg", 
					   "pictures/bikes/2016/mtb/Talon/Talon-27.5-3/Talon-27-5-3-Charcoal.jpg",
					   "pictures/bikes/2016/mtb/Talon/Talon-27.5-4/Talon-275-4-Charcoal.jpg",
					   "pictures/bikes/2016/mtb/Talon/Talon-29er/Talon-29er-2-Dark-Blue.jpg",
					   "pictures/bikes/2016/mtb/ATX/ATX-275-2-Black-Red.jpg", 
					   "pictures/bikes/2016/mtb/Revel/Revel-2/Revel-2-Black.jpg",
					   "pictures/bikes/2016/mtb/Revel/Revel-29er/Revel-29er-2.jpg"];

var bike_titles_giant = ["Giant Anthem Advanced 27.5 0",
						 "Giant Anthem Advanced 27.5 1",
						 "Giant Anthem Advanced 27.5 2",
						 "Giant Anthem Advanced SX 27.5",
						 "Giant Anthem 27.5 2",
						 "Giant Anthem SX 27.5",
						 "Giant Anthem X Advanced 29er",
						 "Giant Anthem X 29er",
						 "Giant XTC Advanced SL 27.5 0",
						 "Giant XTC Advanced SL 27.5 1",
						 "Giant XTC Advanced 27.5 1",
						 "Giant XTC Advanced 27.5 3",
						 "Giant XTC Advanced 29er 1",
						 "Giant XTC Advanced 29er 2",
						 "Giant Trance Advanced 27.5 0",
						 "Giant Trance Advanced 27.5 1",
						 "Giant Trance Advanced 27.5 2",
						 "Giant Trance 27.5 1",
						 "Giant Trance 27.5 2",
						 "Giant Trance 27.5 3",
						 "Giant Trance SX 27.5",
						 "Giant Stance 27.5 1",
						 "Giant Stance 27.5 2",
						 "Giant Reign Advanced 27.5 0",
						 "Giant Reign Advanced 27.5 1",
						 "Giant Reign 27.5 1",
						 "Giant Reign 27.5 2",
						 "Giant Talon 27.5 1",
						 "Giant Talon 27.5 2",
						 "Giant Talon 27.5 3",
						 "Giant Talon 27.5 4",
						 "Giant Talon 29er",
						 "Giant ATX 27.5 2",
						 "Giant Revel 2",
						 "Giant Revel 29er"];

var bike_descriptions_giant = ["Lightning fast XC speed with total control on rough terrain. Stay out front with this superlight composite XC racer.<br><strong>$9500</strong>",
							   "Lightning fast XC speed with total control on rough terrain. Stay out front with this superlight composite XC racer.<br><strong>$4800</strong>",
							   "Lightning fast XC speed with total control on rough terrain. Stay out front with this superlight composite XC racer.<br><strong>$3100</strong>",
							   "XC speed with added confidence and control. Fly up steep climbs, bomb down technical trails.<br><strong>$5600</strong>",
							   "From daily trail rides to weekend races, this versatile 27.5 machine is an XC ninja with speed and control.<br><strong>$2600</strong>",
							   "A proven XC slayer with a trick up its sleeve. Fast up the climbs, even faster on aggressive, technical trails.<br><strong>$3000</strong>",
							   "Race-ready XC speed meets 29er stability. Incredible traction on the climbs, added confidence on the descents.<br><strong>$4600</strong>",
							   "Smooth, stable and in control. Crush technical terrain with this confident XC roller.<br><strong>$2700</strong>",
							   "Pure XC speed, born on the World Cup circuit. This is the fastest way up, down, and all around any racetrack or trail.<br><strong>$8900</strong>",
							   "Pure XC speed, born on the World Cup circuit. This is the fastest way up, down, and all around any racetrack or trail.<br><strong>$4600</strong>",
							   "Turn up the heat on XC terrain. Hammer up climbs, rail through corners, feel total control on every descent.<br><strong>$4100</strong>",
							   "Turn up the heat on XC terrain. Hammer up climbs, rail through corners, feel total control on every descent.<br><strong>$2100</strong>",
							   "A lightweight composite frame with stable 29er handlling. It's the perfect combo for fast XC riding or racing.<br><strong>$3000</strong>",
							   "A lightweight composite frame with stable 29er handlling. It's the perfect combo for fast XC riding or racing.<br><strong>$2100</strong>",
							   "Float through climbs and rail rowdy descents. This high-performance trail machine is engineered to do it all.<br><strong>$7700</strong>",
							   "Float through climbs and rail rowdy descents. This high-performance trail machine is engineered to do it all.<br><strong>$5000</strong>",
							   "Float through climbs and rail rowdy descents. This high-performance trail machine is engineered to do it all.<br><strong>$3300</strong>",
							   "More control on steep, aggressive terrain. Power and speed on technical climbs. Pure confidence for every type of trial.<br><strong>$4600</strong>",
							   "More control on steep, aggressive terrain. Power and speed on technical climbs. Pure confidence for every type of trial.<br><strong>$2700</strong>",
							   "More control on steep, aggressive terrain. Power and speed on technical climbs. Pure confidence for every type of trial.<br><strong>$2100</strong>",
							   "From backcountry epics to weekend enduro races. Here's your ticket to fun on fast, technical trails.<br><strong>$4500</strong>",
							   "When the trail calls, Stance 27.5 answers. Confident, quick, and fun to ride, it opens up a world of off-road possibilities.<br><strong>$1900</strong>",
							   "When the trail calls, Stance 27.5 answers. Confident, quick, and fun to ride, it opens up a world of off-road possibilities.<br><strong>$1500</strong>",
							   "Enduro, all-mountain, black diamond descents. Big climbs and burly descents, that's what this bike is made for.<br><strong>$8300</strong>",
							   "Enduro, all-mountain, black diamond descents. Big climbs and burly descents, that's what this bike is made for.<br><strong>$5500</strong>",
							   "Stay smooth with things get rough. Rocks, roots, ruts - whatever comes your way, you're ready with Reign 27.5.<br><strong>$5350</strong>",
							   "Stay smooth with things get rough. Rocks, roots, ruts - whatever comes your way, you're ready with Reign 27.5.<br><strong>$3410</strong>",
							   "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$1400</strong>",
							   "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$1200</strong>",
							   "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$700</strong>",
							   "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$600</strong>",
							   "Smooth and stable. A classic 29er hardtail made to roll through rough stuff with added balance and flow.<br><strong>$850</strong>",
							   "On-road or off-road, the choice is yours. With smooth, confident 27.5 wheels, this is your invitation to explore.<br><strong>$460</strong>",
							   "Smooth, dependable and designed to make trail riding more fun. Blaze new trails with this 29er.<br><strong>$570</strong>",
							   "Take a spin on the bike path or head into the forest. For aspiring off-road riders, Revel lets you blaze new trails.<br><strong>$370</strong>"];

var bike_modal_titles_giant = ["Giant Anthem X 29er",
							   "Giant Trance 27.5 2",
							   "Giant Trance 27.5 3",
							   "Giant Stance 27.5 2",
							   "Giant Talon 27.5 1",
							   "Giant Talon 27.5 2",
							   "Giant Talon 27.5 3",
							   "Giant ATX 27.5 2",
							   "Giant Revel 2"];

var bike_modal_descriptions_giant = ["<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640304"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600305"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600306"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640304"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600302"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640302"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640305"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640303"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600336"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600337"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600333"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600335"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640311"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640312"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600330"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600331"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600332"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600327"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600328"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600329"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640309"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600325"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600326"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600323"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600324"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600321"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600322"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600402"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600403"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600404"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600405"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=640402"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600516"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600411"></iframe>",
									 "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=616403"></iframe>"];

// Liv Brand
var num_items_liv = 14;

var bike_pics_liv = ["pictures/bikes/2016/mtb/Lust/Lust-Adv-0/Lust-Advanced-0-Carbon.jpg",
					 "pictures/bikes/2016/mtb/Lust/Lust-Adv-1/Lust-Advanced-1-Carbon.jpg",
					 "pictures/bikes/2016/mtb/Lust/Lust-Adv-2/Lust-Advanced-2-Blue.jpg",
					 "pictures/bikes/2016/mtb/Lust/Lust-1/Lust-1-Blue.jpg",
					 "pictures/bikes/2016/mtb/Lust/Lust-2/Lust-2-Black-Pink.jpg",
					 "pictures/bikes/2016/mtb/Obsess/Obsess-Adv-2/Obsess-Advanced-2-Comp.jpg",
					 "pictures/bikes/2016/mtb/Intrigue/Intrigue-1/Intrigue-1-Black.jpg",
					 "pictures/bikes/2016/mtb/Intrigue/Intrigue-SX/Intrigue-SX-Blue.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-1/Tempt-1-Black.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-2/Tempt-2-White.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-3/Tempt-3-Dark-Green.jpg",
					 "pictures/bikes/2016/mtb/Tempt/Tempt-4/Tempt-4-Black.jpg",
					 "pictures/bikes/2016/mtb/Enchant/Enchant-1/Enchant-1-Black-Purple.jpg",
					 "pictures/bikes/2016/mtb/Enchant/Enchant-2/Enchant-2-White-Blue.jpg"];

var bike_titles_liv = ["Liv Lust Advanced 0",
					   "Liv Lust Advanced 1",
					   "Liv Lust Advanced 2",
					   "Liv Lust 1",
					   "Liv Lust 2",
					   "Liv Obsess Advanced 2",
					   "Liv Intrigue 1",
					   "Liv Intrigue SX",
					   "Liv Tempt 1",
					   "Liv Tempt 2",
					   "Liv Tempt 3",
					   "Liv Tempt 4",
					   "Liv Enchant 1",
					   "Liv Enchant 2"];

var bike_descriptions_liv = ["Uncompromising performance on the most challenging singletrack. Take your trail riding to the next level.<br><strong>$9000</strong>",
							 "Uncompromising performance on the most challenging singletrack. Take your trail riding to the next level.<br><strong>$9000</strong>",
							 "Uncompromising performance on the most challenging singletrack. Take your trail riding to the next level.<br><strong>$3100</strong>",
							 "The trifecta of less weight, more control, and increased efficiency equals a fun and confident XC bike.<br><strong>$2900</strong>",
							 "The trifecta of less weight, more control, and increased efficiency equals a fun and confident XC bike.<br><strong>$2500</strong>",
							 "Your obsession with XC racing starts here. Obsess is ready to tackle singletrack with precision and agility.<br><strong>$2700</strong>",
							 "Unleash your potential on technical trails. This women's-specific trail bike helps you take your skills to new heights.<br><strong>$3200</strong>",
							 "Rocks, roots, fearsome terrain. The smooth and stable Intrigue SX gives you the upper hand on technical trails.<br><strong>$4475</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$1400</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$1100</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$700</strong>",
							 "Make your first foray into the dirt or graduate to advanced singletrack. Tempt is designed to be with you all the way.<br><strong>$600</strong>",
							 "Become enchanted with cycling on roads, paths or dirt. The versatile and capable enchant.<br><strong>$430</strong>",
							 "Become enchanted with cycling on roads, paths or dirt. The versatile and capable enchant.<br><strong>$370</strong>"];

var bike_modal_titles_liv = ["Live Lust 1",
				   			 "Liv Lust 2",
				   			 "Liv Tempt 1",
							 "Liv Tempt  2",
							 "Liv Tempt 3",
							 "Liv Tempt 4",
							 "Liv Enchant 1",
							 "Liv Enchant 2"];

var bike_modal_descriptions_liv = ["<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600316"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600317"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600318"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600314"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600315"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600320"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600311"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600313"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600416"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600407"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600408"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600409"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600517"></iframe>",
								   "<iframe style="border:none" width="710" height="700" src="https://www.giantretailacademy.com/go/?c=US&axid=600518"></iframe>"];

// Kona Brand
var num_items_kona = 4;

var bike_pics_kona = ["pictures/bikes/2016/mtb/Anthem/Anthem-X-29er/Anthem-X-29er-Black.jpg",
					  "pictures/bikes/2016/mtb/Trance/Trance-27.5-2/Trance-275-2-Charcoal.jpg",
					  "pictures/bikes/2016/mtb/Trance/Trance-27.5-3/Trance-275-3-Black.jpg",
					  "pictures/bikes/2016/mtb/Stance/Stance-27.5-2/Stance-275-2-Black.jpg",
					  "pictures/bikes/2016/mtb/Talon/Talon-27.5-1/Talon-275-1-Black-Green.jpg",
					  "pictures/bikes/2016/mtb/Talon/Talon-27.5-2/Talon-275-2-Silver-Blue.jpg", 
					  "pictures/bikes/2016/mtb/Talon/Talon-27.5-3/Talon-27-5-3-Charcoal.jpg",
					  "pictures/bikes/2016/mtb/ATX/ATX-275-2-Black-Red.jpg", 
					  "pictures/bikes/2016/mtb/Revel/Revel-2/Revel-2-Black.jpg"];

var bike_titles_kona = ["Kona",
						"Kona",
						"Giant Trance 27.5 3",
						"Giant Stance 27.5 2",
						"Giant Talon 27.5 1",
						"Giant Talon 27.5 2",
						"Giant Talon 27.5 3",
						"Giant ATX 27.5 2",
						"Giant Revel 2"];

var bike_descriptions_kona = ["Smooth, stable and in control. Crush technical terrain with this confident XC roller.<br><strong>$2700</strong>",
							  "More control on steep, aggressive terrain, power and speed on technical climbs. Pure confidence for every type of trail.<br><strong>$2700</strong>",
							  "More control on steep, aggressive terrain, power and speed on technical climbs. Pure confidence for every type of trail.<br><strong>$2100</strong>",
							  "When the trail calls, Stance 27.5 answers. Confident, quick and fun to ride, it opens up a world of off-road possibilities.<br><strong>$1500</strong>",
							  "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$1400</strong>",
							  "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$1100</strong>",
							  "Crank up tricky climbs and carve through corners. This balanced 27.5 hardtail lets you hit the trail with confidence.<br><strong>$700</strong>",
							  "On-road or off-road, the choice is yours. With smooth, confident 27.5 wheels, this is your invitation to explore.<br><strong>$460</strong>",
							  "Take a spin on the bike path or head into the forest. For aspiring off-road riders, revel lets you blaze new trails.<br><strong>$370</strong>"];

var bike_modal_titles_kona = ["Giant Anthem X 29er",
							  "Giant Trance 27.5 2",
							  "Giant Trance 27.5 3",
							  "Giant Stance 27.5 2",
							  "Giant Talon 27.5 1",
							  "Giant Talon 27.5 2",
							  "Giant Talon 27.5 3",
							  "Giant ATX 27.5 2",
							  "Giant Revel 2"];

var bike_modal_descriptions_kona = ["This is a test modal body",
									"This is a test modal body",
									"This is a test modal body",
									"This is a test modal body",
									"This is a test modal body",
									"This is a test modal body",
									"This is a test modal body",
									"This is a test modal body",
									"This is a test modal body"];*/

?>