<?php
	$buttonNum = $_POST['num'];
	$num_items_giant = 38;
	$bike_pics_giant = array("pictures/bikes/2016/road/Propel/Propel-Adv-SL-0/Propel-Advanced-SL-0-Comp.jpg",
					 "pictures/bikes/2016/road/Propel/Propel-Adv-SL-Team/Propel-Adv-SL-Team.jpg",
					 "pictures/bikes/2016/road/Propel/Propel-Adv-SL-1/Propel-Advanced-SL-1-Blue.jpg",
					 "pictures/bikes/2016/road/Propel/Propel-Adv-SL-2/Propel-Advanced-SL-2-Comp-Red.jpg",
					 "pictures/bikes/2016/road/Propel/Propel-Adv-Pro-0/Propel-Advanced-Pro-0-Comp.jpg",
					 "pictures/bikes/2016/road/Propel/Propel-Adv-0/Propel-Advanced-0-Comp.jpg", 
					 "pictures/bikes/2016/road/Propel/Propel-Adv-1/Propel-Advanced-1-Comp.jpg",
					 "pictures/bikes/2016/road/Propel/Propel-Adv-2/Propel-Advanced-2-Comp-White.jpg", 
					 "pictures/bikes/2016/road/TCR/TCR-Adv-SL-0/TCR-Advanced-SL-0-Copmp-Cyan.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-SL-1/TCR-Advanced-SL-1-Comp-Red.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-SL-2/TCR-Advanced-SL-2-Lime-Black.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-Pro-0/TCR-Advanced-Pro-0-Comp-Black.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-Pro-1/TCR-Advanced-Pro-1-Comp-Cyan.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-1/TCR-Advanced-1-Comp-Lime.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-2/TCR-Advanced-2-Comp-Red.jpg",
					 "pictures/bikes/2016/road/TCR/TCR-Adv-3/TCR-Advanced-3-Comp-Yellow.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-SL-0/Defy-Advanced-SL-0-Comp-Blue.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-SL-1/Defy-Advanced-SL-1-Comp-Red.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-Pro-0/Defy-Advanced-Pro-0-Comp.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-Pro-2/Defy-Advanced-Pro-2-Blue.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-1/Defy-Advanced-1-Comp-Cyan.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-2/Defy-Advanced-2-Comp-Lime.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-Adv-3/Defy-Advanced-3-Comp.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-1/Defy-1-Disc-Blue.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-2/Defy-2-Disc-Black.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-3/Defy-3-White.jpg",
					 "pictures/bikes/2016/road/Defy/Defy-5/Defy-5-Black-Red.jpg",
					 "pictures/bikes/2016/road/Fastroad/Fastroad-Comax-1/FastRoad-CoMax-1.jpg",
					 "pictures/bikes/2016/road/Fastroad/Fastroad-Comax-2/FastRoad-CoMax-2-Comp-Blue.jpg",
					 "pictures/bikes/2016/road/Fastroad/Fastroad-SLR-1/FastRoad-SLR-1-Black.jpg",
					 "pictures/bikes/2016/road/Escape/Escape-1/Escape-1-Black.jpg",
					 "pictures/bikes/2016/road/Escape/Escape-2/Escape-2-Gray.jpg",
					 "pictures/bikes/2016/road/Escape/Escape-2-City/Escape-2-City-Gray.jpg",
					 "pictures/bikes/2016/road/Escape/Escape-3/Escape-3-Black.jpg",
					 "pictures/bikes/2016/road/Cypress/Cypress-DX/Cypress-DX-Dark-Gray.jpg",
					 "pictures/bikes/2016/road/Cypress/Cypress/Cypress-Black.jpg",
					 "pictures/bikes/2016/road/Simple/Three/Simple-Three-Green.jpg",
					 "pictures/bikes/2016/road/Simple/Single/Simple-Single-Red-Black.jpg");

	$bike_titles_giant = array("Giant Propel Advanced SL 0",
					   "Giant Propel Advanced SL Team",
					   "Giant Propel Advanced SL 1",
					   "Giant Propel Advanced SL 2",
					   "Giant Propel Advanced Pro 0",
					   "Giant Propel Advanced 0",
					   "Giant Propel Advanced 1",
					   "Giant Propel Advanced 2",
					   "Giant TCR Advanced SL 0",
					   "Giant TCR Advanced SL 1",
					   "Giant TCR Advanced SL 2",
					   "Giant TCR Advanced Pro 0",
					   "Giant TCR Advanced Pro 1",
					   "Giant TCR Advanced 1",
					   "Giant TCR Advanced 2",
					   "Giant TCR Advanced 3",
					   "Giant Defy Advanced SL 0",
					   "Giant Defy Advanced SL 1",
					   "Giant Defy Advanced Pro 0",
					   "Giant Defy Advanced Pro 2",
					   "Giant Defy Advanced 1",
					   "Giant Defy Advanced 2",
					   "Giant Defy Advanced 3",
					   "Giant Defy 1 Disc",
					   "Giant Defy 2 Disc",
					   "Giant Defy 3",
					   "Giant Defy 5",
					   "Giant Fastroad CoMax 1",
					   "Giant Fastroad CoMax 2",
					   "Giant Fastroad SLR 1",
					   "Giant Escape 1",
					   "Giant Escape 2",
					   "Giant Escape 2 City",
					   "Giant Escape 3",
					   "Giant Cypress DX",
					   "Giant Cypress",
					   "Giant Simple Three",
					   "Giant Simple Single");

	$bike_descriptions_giant = array("This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$9000</strong>",
							 "This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$6900</strong>",
							 "This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$6900</strong>",
							 "This pro peleton standout is the pinnacle of aero road. A killer in the sprints, with sublime overall ride quality.<br><strong>$4400</strong>",
							 "A perfect blend of aero efficiency and all-around ride quality. For the spring, the chase, the thrill of speed.<br><strong>$5650</strong>",
							 "Get up to speed and slice through the wind. Whether springing to win or riding solo, give yourself the aero edge.<br><strong>$4000</strong>",
							 "Get up to speed and slice through the wind. Whether springing to win or riding solo, give yourself the aero edge.<br><strong>$2600</strong>",
							 "Get up to speed and slice through the wind. Whether springing to win or riding solo, give yourself the aero edge.<br><strong>$2100</strong>",
							 "Fly up steep climbs. Attack twisting descents. Now lighter and more efficient, this reengineered pro legend is the total race bike.<br><strong>$9000</strong>",
							 "Fly up steep climbs. Attack twisting descents. Now lighter and more efficient, this reengineered pro legend is the total race bike.<br><strong>$5900</strong>",
							 "Fly up steep climbs. Attack twisting descents. Now lighter and more efficient, this reengineered pro legend is the total race bike.<br><strong>$4100</strong>",
							 "From long, hard training rides to critical moments in a race. This is total race performance, made for your podium quest.<br><strong>$5500</strong>",
							 "From long, hard training rides to critical moments in a race. This is total race performance, made for your podium quest.<br><strong>$3500</strong>",
							 "Race-winning efficiency. Improved ride quality. Agile geometry. New and updated, the total race bike for road.<br><strong>$2500</strong>",
							 "Race-winning efficiency. Improved ride quality. Agile geometry. New and updated, the total race bike for road.<br><strong>$2000</strong>",
							 "Race-winning efficiency. Improved ride quality. Agile geometry. New and updated, the total race bike for road.<br><strong>$1700</strong>",
							 "Peak performance to push yourself farther. Superlight and smooth riding, this is the new standard for endurance road.<br><strong>$8300</strong>",
							 "Peak performance to push yourself farther. Superlight and smooth riding, this is the new standard for endurance road.<br><strong>$4600</strong>",
							 "No gimmicks, just superior engineering for compliance and control. Ride faster, ride farther on all types of roads.<br><strong>$5100</strong>",
							 "No gimmicks, just superior engineering for compliance and control. Ride faster, ride farther on all types of roads.<br><strong>$3200</strong>",
							 "Hammer out more miles, descend with more confidence. From Gran Fondos to epic solo rides, Defy Advanced helps you finish strong.<br><strong>$2600</strong>",
							 "Hammer out more miles, descend with more confidence. From Gran Fondos to epic solo rides, Defy Advanced helps you finish strong.<br><strong>$2100</strong>",
							 "Hammer out more miles, descend with more confidence. From Gran Fondos to epic solo rides, Defy Advanced helps you finish strong.<br><strong>$1800</strong>",
							 "Light and lively road performance with an added boost of compliance and control. Smooth, fast and fun to ride.<br><strong>$1500</strong>",
							 "Light and lively road performance with an added boost of compliance and control. Smooth, fast and fun to ride.<br><strong>$1200</strong>",
							 "Get fit, get fast, and get more miles with this lightweight, smooth and comfortable aluminum road machine.<br><strong>$920</strong>",
							 "Get fit, get fast, and get more miles with this lightweight, smooth and comfortable aluminum road machine.<br><strong>$640</strong>",
							 "Get up to speed with less effort and more fun. This sporty, smooth-riding flat-bar road bike is pure exhiliration.<br><strong>$1800</strong>",
							 "Get up to speed with less effort and more fun. This sporty, smooth-riding flat-bar road bike is pure exhiliration.<br><strong>$1500</strong>",
							 "So smooth, so efficient, it feels like flying. A sleek road bike meets flat-bar positioning. Super versatile, super fun.<br><strong>$1100</strong>",
							 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$670</strong>",
							 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$460</strong>",
							 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$590</strong>",
							 "A fast, fun way to get around town. Ride it to work, to school, or just for the thrill of it.<br><strong>$360</strong>",
							 "Comfort, control and the joy of a bike ride. Cypress helps you get outside, get healthy and get where you want to go.<br><strong>$440</strong>",
							 "Comfort, control and the joy of a bike ride. Cypress helps you get outside, get healthy and get where you want to go.<br><strong>$340</strong>",
							 "Hop on, spin the pedals, and feel the stress melt away. Class cruiser style meets modern comfort and design.<br><strong>$490</strong>",
							 "Hop on, spin the pedals, and feel the stress melt away. Class cruiser style meets modern comfort and design.<br><strong>$330</strong>");

	$bike_modal_descriptions_giant = array("<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600043\"></iframe>",
							        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=615001\"></iframe>",
							        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600044\"></iframe>",
							       "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600045\"></iframe>",
							        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600040\"></iframe>",
							        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600020\"></iframe>",
							       "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600021\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600022\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600052\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600053\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600054\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600049\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600050\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600046\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600047\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600048\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600034\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600035\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600031\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600033\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600015\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600016\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600017\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600029\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600030\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600012\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600014\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600115\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600116\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600117\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600111\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600112\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600113\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600114\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600203\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600201\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600216\"></iframe>",
					   		        "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600214\"></iframe>");

	// Liv Brand
	$num_items_liv = 24;

	$bike_pics_liv = array("pictures/bikes/2016/road/Envie/Envie-Adv-Pro-0/Envie-Advanced-Pro-0-White-Purple.jpg",
						 "pictures/bikes/2016/road/Envie/Envie-Adv-Pro-1/Envie-Advanced-Pro-1-Black.jpg",
						 "pictures/bikes/2016/road/Envie/Envie-Adv-Tri-1/Envie-Advanced-TRI-1-Comp.jpg",
						 "pictures/bikes/2016/road/Envie/Envie-Adv-Tri-2/Envie-Advanced-TRI-2-White-Pink.jpg",
						 "pictures/bikes/2016/road/Envie/Envie-Adv-1/Envie-Advanced-1-White-Blue.jpg",
						 "pictures/bikes/2016/road/Envie/Envie-Adv-2/Envie-Advanced-2-White-Silver.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-Adv-SL/Avail-Advanced-SL-Comp.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-Adv-Pro/Avail-Advanced-Pro-Comp.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-Adv-1/Avail-Advanced-1-Comp.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-Adv-2/Avail-Advanced-2-Pearl-White.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-Adv-3/Avail-Advanced-3-White-Angle.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-1-Disc/Avail-1-Disc-Dark-Blue.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-2-Disc/Avail-2-Disc-Silver.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-3/Avail-3-Black.jpg",
						 "pictures/bikes/2016/road/Avail/Avail-4/Avail-4-White.jpg",
						 "pictures/bikes/2016/road/Thrive/Thrive-Comax-1/Thrive-CoMax-1-Disc-Chaocoal.jpg",
						 "pictures/bikes/2016/road/Thrive/Thrive-Comax-2/Thrive-CoMax-2-Disc-Blue.jpg",
						 "pictures/bikes/2016/road/Thrive/Thrive-1/Thrive-1-Disc-White-Purple.jpg",
						 "pictures/bikes/2016/road/Alight/Alight-1/Alight-1-DD-Black.jpg",
						 "pictures/bikes/2016/road/Alight/Alight-City/Alight-2-DD-City-Silver.jpg",
						 "pictures/bikes/2016/road/Alight/Alight-2/Alight-2-DD-Dark-Blue.jpg",
						 "pictures/bikes/2016/road/Alight/Alight-3/Alight-3-Blue.jpg",
						 "pictures/bikes/2016/road/Simple-W/Simple-Three-W/Simple-Three-W-White.jpg",
						 "pictures/bikes/2016/road/Simple-W/Simple-Single-W/Simple-Single-W-Blue.jpg");

	$bike_titles_liv = array("Liv Envie Advanced Pro 0",
						   "Liv Envie Advanced Pro 1",
						   "Liv Envie Advanced 1 Tri",
						   "Liv Envie Advanced 2 Tri",
						   "Liv Envie Advanced 1",
						   "Liv Envie Advanced 2",
						   "Liv Avail Advanced SL",
						   "Liv Avail Advanced Pro",
						   "Liv Avail Advanced 1",
						   "Liv Avail Advanced 2",
						   "Liv Avail Advanced 3",
						   "Liv Avail 1 Disc",
						   "Liv Avail 2 Disc",
						   "Liv Avail 3",
						   "Liv Avail 4",
						   "Liv Thrive CoMax 1",
						   "Liv Thrive CoMax 2",
						   "Liv Thrive 1",
						   "Liv Alight 1",
						   "Liv Alight City",
						   "Liv Alight 2",
						   "Liv Alight 3",
						   "Liv Simple Three W",
						   "Liv Simple Single W");

	$bike_descriptions_liv = array("A proven winner with big-time race victories, this is the reigning queen of aero road. Attack, spring, get that podium.<br><strong>$8300</strong>",
								 "A proven winner with big-time race victories, this is the reigning queen of aero road. Attack, spring, get that podium.<br><strong>$5350</strong>",
								 "A tri machine that's made just for women. Speed, aerodynamics and the perfect fit. That's the winning formula.<br><strong>$3400</strong>",
								 "A tri machine that's made just for women. Speed, aerodynamics and the perfect fit. That's the winning formula.<br><strong>$2300</strong>",
								 "Designed to harness the power of women riders, this aero road machine slices through wind. Get on and get ahead of the pack.<br><strong>$2600</strong>",
								 "Designed to harness the power of women riders, this aero road machine slices through wind. Get on and get ahead of the pack.<br><strong>$2100</strong>",
								 "Bring the bliss back to road riding with the lightweight Avail Advanced SL. Pro performance for faster, longer road rides.<br><strong>$5900</strong>",
								 "An endurance road bike that's smooth, fast and made for women riders. Precise fit, superior ride quality.<br><strong>$3750</strong>",
								 "From epic solo adventures to fast group road rides. Light, fast and engineered just for women.<br><strong>$2600</strong>",
								 "From epic solo adventures to fast group road rides. Light, fast and engineered just for women.<br><strong>$2100</strong>",
								 "From epic solo adventures to fast group road rides. Light, fast and engineered just for women.<br><strong>$1800</strong>",
								 "For quick spins or epic rides, Avail Disc is the perfect road companion. Speed, control, confidence. Choose all three.<br><strong>$1500</strong>",
								 "For quick spins or epic rides, Avail Disc is the perfect road companion. Speed, control, confidence. Choose all three.<br><strong>$1200</strong>",
								 "The right companion for any challenge on the road. Avail helps you go farther, faster.<br><strong>$920</strong>",
								 "The right companion for any challenge on the road. Avail helps you go farther, faster.<br><strong>$640</strong>",
								 "A flat-bar road bike that's light, speedy and designed for women. Build confidence on the road and get fit faster.<br><strong>$1800</strong>",
								 "A flat-bar road bike that's light, speedy and designed for women. Build confidence on the road and get fit faster.<br><strong>$1500</strong>",
								 "From short daily spins to longer road rides, Thrive is a fast, fun and confident fitness bike.<br><strong>$950</strong>",
								 "Pedal to work, meet for coffee, or build your fitness out on the bike path. Alight fits right into a healthy lifestyle.<br><strong>$670</strong>",
								 "Pedal to work, meet for coffee, or build your fitness out on the bike path. Alight fits right into a healthy lifestyle.<br><strong>$590</strong>",
								 "Pedal to work, meet for coffee, or build your fitness out on the bike path. Alight fits right into a healthy lifestyle.<br><strong>$460</strong>",
								 "Pedal to work, meet for coffee, or build your fitness out on the bike path. Alight fits right into a healthy lifestyle.<br><strong>$360</strong>",
								 "Every ride is like a mini vacation. The comfort and classic style of Simple W can bring a beach vibe to everyday life.<br><strong>$490</strong>",
								 "Every ride is like a mini vacation. The comfort and classic style of Simple W can bring a beach vibe to everyday life.<br><strong>$330</strong>",);

	$bike_modal_titles_liv = array("Live Lust 1",
					   			 "Liv Lust 2",
					   			 "Liv Tempt 1",
								 "Liv Tempt  2",
								 "Liv Tempt 3",
								 "Liv Tempt 4",
								 "Liv Enchant 1",
								 "Liv Enchant 2");

	$bike_modal_descriptions_liv = array("<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600036\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600037\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600038\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600039\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600018\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600019\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600025\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600024\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600007\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600008\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600009\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600002\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600004\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600005\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600006\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600126\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600127\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600123\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600101\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600105\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600104\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600106\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600217\"></iframe>",
									   "<iframe style=\"border:none\" width=\"710\" height=\"700\" src=\"https://www.giantretailacademy.com/go/?c=US&axid=600215\"></iframe>");
?>